services:
  nextjs-app:
    container_name: my-next-app
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app:delegated
      - next_node_modules:/app/node_modules  ## this was the lucide-react issue

    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true

volumes:
  next_node_modules: